### ISSUE TITLE
Chaper10/Start does not contain the barebones CustomerSearch component or tests

### ISSUE THREAD

**Issue by GaeaKat** [PacktPublishing/Mastering-React-Test-Driven-Development-Second-Edition#3]
The book associated says there is a barebones CustomerSearch component and test in the github. unfortunatly there is only the completed one for Chapter10

**Comment by dirv** [comment]
Hi, thanks for reporting this. I’ll need to regenerate Chapter10/Start which I can’t do right now as I’m not at my laptop. 

However if it helps you to get moving, I believe this is the intended commit:

https://github.com/PacktPublishing/Mastering-React-Test-Driven-Development-Second-Edition/commit/018ba015088d4ab84c0ff7585af3b83978ec1784

(Each of the chapter folders is generated from a specific commit in the appointments or spec-logo branches).

I’ll leave another comment once Chapter10/Start has been fixed.

**Comment by dirv** [comment]
I've pushed a new version of `Chapter10/Start`. I think the code looks okay but haven't had the time to double check with the book text. If there's still an issue please do reopen the ticket and I'll take a more detailed look.
