### ISSUE TITLE
Update handleSubmit method in chapter 4: Submitting a form [In Book]

### ISSUE THREAD

**Issue by Harsh-0-7** [PacktPublishing/Mastering-React-Test-Driven-Development-Second-Edition#4]
So in chapter 4:Accepting text input,
handleSubmit method was updated as 
	const handleSubmit = (event) => {
		event.preventDefault();
		onSubmit(original);
	};

But in next section "Submitting a form -> Submitting changed values",it is should be 
	const handleSubmit = (event) => {
		event.preventDefault();
		onSubmit(customer);
	};
But this part is not mentioned in that section.Due to which i was getting error.

Github code is fine.Only book needs change.
Thank you for this awesome book :)

**Comment by dirv** [comment]
Thanks for the bug report - I will get this added to the Errata.
I really appreciate the feedback, and I'm glad you're enjoying the book :)
